create table knowledge_components (kc_id uuid not null, description varchar(255), kc_name varchar(255), primary key (kc_id));
create table lesson_kc_mapping (target_mastery bigint not null, kc_id uuid not null, lesson_id uuid not null, primary key (kc_id, lesson_id));
create table lessons (lesson_id uuid not null, module_id uuid, description varchar(255), lesson_name varchar(255), primary key (lesson_id));
create table modules (module_id uuid not null, description varchar(255), module_name varchar(255), primary key (module_id));
create table multiple_choice_questions (question_id uuid not null, correct_option_key varchar(255), options jsonb, primary key (question_id));
create table question_kc_mapping (weight float(53) not null, kc_id uuid not null, question_id uuid not null, primary key (kc_id, question_id));
create table questions (question_id uuid not null, question_type varchar(31) not null, hint_level_1 varchar(255), hint_level_2 varchar(255), question_text varchar(255), primary key (question_id));
create table scaffolds (order_index integer not null, question_id uuid not null, scaffold_id uuid not null, scaffold_correct_answer varchar(255), scaffold_text varchar(255), primary key (scaffold_id));
create table session (created_at timestamp(6) with time zone not null, end_time timestamp(6) with time zone, start_time timestamp(6) with time zone, updated_at timestamp(6) with time zone, session_id uuid not null, user_id uuid, device_type varchar(255), user_agent varchar(255), primary key (session_id));
create table student_interactions (hint_level integer not null, is_correct boolean not null, p_mastery float(53) not null, time_spent_seconds integer not null, timestamp timestamp(6) with time zone, interaction_id uuid not null, kc_id uuid, lesson_id uuid, question_id uuid, scaffold_id uuid, session_id uuid, user_id uuid, interaction_type varchar(255) check (interaction_type in ('LESSON_START','LESSON_EXIT','START_TEST','TEST_EXIT','QUIZ_ANSWER','HINT_REQUEST','SCAFFOLD_ANSWER')), student_answer varchar(255), primary key (interaction_id));
create table studentkcmastery (p_guess float(53) not null, p_mastery float(53) not null, p_slip float(53) not null, p_transit float(53) not null, updated_at timestamp(6) with time zone, kc_id uuid not null, user_id uuid not null, primary key (kc_id, user_id));
create table users (created_at timestamp(6) with time zone, updated_at timestamp(6) with time zone, user_id uuid not null, email varchar(255), google_id varchar(255), image_url varchar(255), username varchar(255), primary key (user_id));
create table written_question_entity (question_id uuid not null, answer_explanation varchar(255), correct_answer_text varchar(255), primary key (question_id));
alter table if exists lesson_kc_mapping add constraint FK8f49irh5rjldyxlj1ovou79n9 foreign key (kc_id) references knowledge_components;
alter table if exists lesson_kc_mapping add constraint FKabv3jfa6e0nv29nb1i6fxnnql foreign key (lesson_id) references lessons;
alter table if exists lessons add constraint FKt9yjhjbd9y3w6fxs66ny1wu02 foreign key (module_id) references modules;
alter table if exists multiple_choice_questions add constraint FK4wm6eckdc1t9ojixpcjq2kxrn foreign key (question_id) references questions;
alter table if exists question_kc_mapping add constraint FKoxgak54glulqmdf40f0mihoya foreign key (kc_id) references knowledge_components;
alter table if exists question_kc_mapping add constraint FKsgelx5xxa6xrdfofc190vu6ht foreign key (question_id) references questions;
alter table if exists scaffolds add constraint FK70wfsajwemt7cxt03feusm067 foreign key (question_id) references questions;
alter table if exists session add constraint FKj3ffkfbfbdoh9uon462ow7lhl foreign key (user_id) references users;
alter table if exists student_interactions add constraint FK6tetw6i1xmx4k0ebpm5uq70sd foreign key (kc_id) references knowledge_components;
alter table if exists student_interactions add constraint FKmk9cd4vrwn90xtq1jii128gic foreign key (lesson_id) references lessons;
alter table if exists student_interactions add constraint FK2qjxxfm5rggiosh3kstghua8d foreign key (question_id) references questions;
alter table if exists student_interactions add constraint FKhgvb24ximmdkgf08obr1utewf foreign key (scaffold_id) references scaffolds;
alter table if exists student_interactions add constraint FK1pfn3iq2a3oqfbii1pexjiv3o foreign key (session_id) references session;
alter table if exists student_interactions add constraint FK4bfb1qpl8csykrlykpaseslg2 foreign key (user_id) references users;
alter table if exists studentkcmastery add constraint FKiu151cbj9madyka00o4reptqy foreign key (kc_id) references knowledge_components;
alter table if exists studentkcmastery add constraint FKf146aqyk1wq3avcuv2gh1d0ou foreign key (user_id) references users;
alter table if exists written_question_entity add constraint FKf5f0e10aam8mqrt7ja2iysog9 foreign key (question_id) references questions;